version: '3'

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
  external:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1


volumes:
  ldap-data:
  ldap-config:
  dns-data:
  dns-config:
  asterisk-config:
  asterisk-data:
  asterisk-log:


services:
  # Service d'adressage dynamique
  dhcp:
    image: networkboot/dhcpd
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - internal
    volumes:
      - /etc/dhcp:/etc/dhcp

  # Sécurité d'accès au réseau en interne
  firewall:
    image: corpusops/ms_iptables
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - internal
    volumes:
      - /etc/iptables:/etc/iptables
    command: >
      /usr/sbin/iptables-restore /etc/iptables/rules.v4

  # Gestion des utilisateurs
  ldap:
    image: osixia/openldap
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
    environment:
      LDAP_ORGANISATION: "Entreprise"
      LDAP_DOMAIN: "entreprise.local"
      LDAP_ADMIN_PASSWORD: "password"

  # DNS de l'entreprise
  dns:
    image: secns/pdns
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - dns-data:/var/lib/pdns
      - dns-config:/etc/pdns
    environment:
      PDNS_ALLOW_AXFR_IPS: "any"
      PDNS_MASTER: "yes"
      PDNS_SLAVE: "no"
      PDNS_API: "yes"
      PDNS_API_KEY: "api-key"
      PDNS_WEBSERVER: "yes"
      PDNS_WEBSERVER_PASSWORD: "password"

  # Service de VoIP
  asterisk:
    image: andrius/asterisk
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - asterisk-config:/etc/asterisk
      - asterisk-data:/var/lib/asterisk
      - asterisk-log:/var/log/asterisk
    ports:
      - "5060:5060/udp"
      - "10000-20000:10000-20000/udp"

  # Autre service applicatif
