version: '3'

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
  external:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1


volumes:
  ldap-data:
  ldap-config:
  dns-data: 
  dns-config:
  dhcp-data: 
  dhcp-config:



services:
  # Service d'adressage dynamique (DHCP)
  dhcp:
    image: networkboot/dhcpd
    restart: unless-stopped
    networks:
      internal:
        ipv4_address: 192.168.0.2
    volumes:
      - C:\Users\Remenby\OneDrive\Bureau\DockerCompose_AS\dhcp-data:/data

  # Sécurité d'accès au réseau en interne
  firewall:
    image: corpusops/ms_iptables
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      ALLOWED_NETWORKS: "192.168.0.0/16,172.16.0.0/12"
      FORWARD_DROP: "true"
      LOG_LEVEL: "warning" 
    networks:
      internal:
        ipv4_address: 192.168.0.4
      external:
        ipv4_address: 10.0.0.2
    volumes:
      - C:\Users\Remenby\OneDrive\Bureau\DockerCompose_AS\iptables:/etc/iptables

  # DNS de l'entreprise
  dns:
    image: secns/pdns
    restart: unless-stopped
    networks:
      internal:
        ipv4_address: 192.168.0.3
    volumes:
      - C:\Users\Remenby\OneDrive\Bureau\DockerCompose_AS\dns-data:/var/lib/pdns
      - C:\Users\Remenby\OneDrive\Bureau\DockerCompose_AS\dns-config:/etc/pdns
    environment:
      PDNS_ALLOW_AXFR_IPS: "any"
      PDNS_MASTER: "yes"
      PDNS_SLAVE: "no"
      PDNS_API: "yes"
      PDNS_API_KEY: "api-key"
      PDNS_WEBSERVER: "yes"
      PDNS_WEBSERVER_PASSWORD: "password"

# Utilisateur Ubuntu
  ubuntu:
    image: ubuntu
    restart: unless-stopped
    command: bash -c "apt-get update && apt-get install -y dhcpcd5 iproute2 && ip a && dhclient -v eth0@if1249 && sleep 1000000"
    tty: true
    stdin_open: true
    networks:
      - internal